pytest-bdd parse step definition matcher
cucumber/language-service pull request #206
Opened 2024-04-23 19:58 UTC by kieran-ryan

### 🤔 What's changed?

- Support the `parse` step definition matcher of `pytest-bdd` - which is also used by `behave`; both Python frameworks

### ⚡️ What's your motivation? 

- Closes #205.

### 🏷️ What kind of change is this?

- :zap: New feature (non-breaking change which adds new behaviour)

### ♻️ Anything particular you want feedback on?

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)
- [x] I've changed the behaviour of the code
  - [ ] I have added/updated tests to cover my changes.
- [x] Users should know about my change
  - [ ] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../blob/main/CHANGELOG.md), linking to this pull request.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

2024-09-21 15:37 UTC, neskk commented
Hello @kieran-ryan,

I've only now turned around and found some time to help test this PR.
- I've added some pytest-bdd parser step definitions to the `StepDefinitions.py` test file.
- I'm a little lost on how can I test the language-service with the modifications in this PR. Are there any instruction on how to run the tests,

2024-12-11 15:11 UTC, vianney-g requested changes

2024-12-11 15:11 UTC, vianney-g commented on src/language/pythonLanguage.ts
> +        function: (identifier) @annotation-name
```suggestion
        function: [(identifier)(attribute)] @annotation-name
```
in case the parser is called as an attribute of a module

2024-12-11 15:11 UTC, vianney-g commented on src/language/pythonLanguage.ts
> +      (#match? @parser "parser")
```suggestion
```

2024-12-11 15:11 UTC, vianney-g commented on src/language/pythonLanguage.ts
> +      (#match? @parser "parser")
```suggestion
```

2024-12-11 15:11 UTC, vianney-g commented on src/language/pythonLanguage.ts
> +            function: (attribute) @parser
```suggestion
            function: [(attribute)(identifier)] @parser
```

2024-12-12 14:33 UTC, neskk commented
Hello @vianney-g, did you manage to test this locally? Are you using pytest-bdd parser syntax:
```
@given(parsers.parse("a stub with {stub_id} exists"))
@given(parsers.parse("a stub exists with:" + os.linesep + "{stub_str}"))
```

I wish to have support for pytest-bdd parser syntax: https://pytest-bdd.readthedocs.io/en/stable/#step-arguments, including support for custom param types.

I can try to run some experiments locally, I just need to grab your changes and install the extension on my dev environment.

2024-12-12 21:37 UTC, vianney-g commented
> Hello @vianney-g, did you manage to test this locally? Are you using pytest-bdd parser syntax:
> 
> ```
> @given(parsers.parse("a stub with {stub_id} exists"))
> @given(parsers.parse("a stub exists with:" + os.linesep + "{stub_str}"))
> ```
> 
> I wish to have support for pytest-bdd parser syntax: https://pytest-bdd.readthedocs.io/en/stable/#step-arguments, including support for custom param types.
> 
> I can try to run some experiments locally, I just need to grab your changes and install the extension on my dev environment.

hi @neskk , ty for your interest.

I was just facing the bug with pytest_bdd and I was wondering how to fix it. Then I discovered your PR. Then I realized it may not match all the cases. I think the query should match the following steps definitions:
```python
import pytest_bdd
from pytest_bdd import given, parsers, when, then
from pytest_bdd.parsers import parse


@pytest_bdd.given(parse("a stub with stub_id exists"))
@given(parse("a stub with {stub_id} exists"))
@when(parsers.parse("a stub with {stub_id} exists"))
@then(parsers.parse("a stub with {stub_id} exists" + " then"))
def test_stub_exists(stub_id):
    assert stub_id == "stub_1"
    return stub_id


@not_a_step(parse("a stub with {stub_id} exists"))
def test_not_match(stub_id):
    assert stub_id == "stub_1"
    return stub_id
```
Please forget my suggestions above. I made some tests locally, and I think the following approach is better to match all the cases (I am not a pro of treesitter queries, I am just playing with):

```
(decorator 
  (call
    arguments: 
    (argument_list
      (call
	arguments:
	(argument_list
	  [(_) @pattern]
	  ) @args
	) @parse
      )
    ) @decorator
  (#match? @decorator "given|when|then")
  (#match? @parse "parse")
  )
```

![image](https://github.com/user-attachments/assets/30d9104f-5047-4c22-80aa-42c62c06cf86)

2024-12-13 15:50 UTC, vianney-g commented
You can adapt the python test file to reflect the different approaches. This patch works for me:

```diff
--- a/src/language/pythonLanguage.ts
+++ b/src/language/pythonLanguage.ts
@@ -95,46 +95,28 @@ export const pythonLanguage: Language = {
     `(decorated_definition
       (decorator
         (call
-          function: (identifier) @method
           arguments: (argument_list (string) @expression)
-        )
+        ) @method
       )
       (#match? @method "(given|when|then|step)")
     ) @root`,
     // pytest-bdd
-    `(decorator
-      (call
-        function: (identifier) @annotation-name
-        arguments: (argument_list
-          (call
-            function: (attribute) @parser
-            arguments: (argument_list
-              [
-                (string) @expression
-              ]
-            )
-          )
-        )
-      )
-      (#match? @annotation-name "given|when|then|step")
-      (#match? @parser "parser")
-    ) @root`,
-    `(decorator
-      (call
-        function: (identifier) @annotation-name
-        arguments: (argument_list
-          (call
-            function: (attribute) @parser
-            arguments: (argument_list
-              [
-                (binary_operator) @expression
-              ]
-            )
-          )
-        )
+    `(decorated_definition
+      (decorator
+        (call
+          arguments:
+          (argument_list
+            (call
+              arguments:
+              (argument_list
+                [(_) @expression]
+              )
+            ) @args
+          ) @parse
       )
-      (#match? @annotation-name "given|when|then|step")
-      (#match? @parser "parser")
+    ) @annotation-name
+    (#match? @annotation-name "given|when|then|step")
+    (#match? @parse "parse")
     ) @root`,
   ],
   snippetParameters: {
diff --git a/test/language/testdata/python/StepDefinitions.py b/test/language/testdata/python/StepDefinitions.py
index cc61457..406e17e 100644
--- a/test/language/testdata/python/StepDefinitions.py
+++ b/test/language/testdata/python/StepDefinitions.py
@@ -1,19 +1,23 @@
 """Port of givens for testdata."""

 from behave import step, given, when, then
+from pytest_bdd.parser import parse
+from pytest_bdd import parser

+import pytest_bdd

-@step("a {uuid}")
+
+@step(parse("a {uuid}"))
 def step_given(context, uuid):
     assert uuid


-@given("a {date}")
+@given(parser.parse("a {date}"))
 def step_date(context, date):
     assert date


-@when("a {planet}")
+@pytest_bdd.when("a {planet}")
 def step_planet(context, planet):
     assert planet
```

2024-12-17 09:25 UTC, vianney-g commented
Hey @neskk ! This is a patch for the branch of this PR. 

I can run the tests with `npm test`, and it works. The compilation step ran successfully on my side. I am on my phone now, I will check again with my laptop if I did something special to make it work.

2025-01-08 03:17 UTC, neskk commented
Happy New Year @vianney-g, 
I finally managed to run the tests using WSL to emulate Linux environment.
I can confirm that your changes seem to work fine in most situations.
One situation where the parsing fails is when the step-def text is a concatenation of strings, e.g.:
```
@then(parse("the" + "bee's" + "knees"))
def step_bees(context, expression):
    """Test Re."""
    assert expression
```

Currently the returned text is: `the" + "bee's" + "knees`, AND, only works when used with the parsers.parse( ) syntax.
I think the original implementation does not attempt to support string concatenation, and for simplification I think we should leave it for a separate MR.

My suggestion is to use the new format, but instead of catching any expressions inside the parse call: `[(_) @expression]`  we use `(string) @expression`.

I realized you made the changes in the first query (non pytest-bdd) to allow something like `@pytest_bdd.when()`, but I also think it's probably not a great pattern to support.

Can you open a MR to push these changes and see if we can get them merged, or you want me to do it?

2025-01-08 16:59 UTC, neskk commented
I just realized that custom params are also not supported:
```python
from parse import with_pattern
from pytest_bdd import parsers, step, given, when, then
from pytest_bdd.parsers import parse

@with_pattern("GET|HEAD|POST|get|head|post")
def http_verb(text: str) -> str:
    return text

custom_types = {
    "valid_http_verb": http_verb,
}

@then(parse("make" + "{http_verb:valid_http_verb} request", custom_types))
def step_bees(context, http_verb):
    """Test Re."""
    assert http_verb
```

Running unit-tests it only captures:
`'ustom_type'`

2025-01-14 10:14 UTC, neskk commented
Hello @kieran-ryan and @vianney-g 
I think I have refined the tree-sitter queries to support both formats (plain/cucumber expressions, and PyPi Parse (pytest-bdd).
I ended up reading a bit of Tree-sitter documentation and I think I managed to develop a nice approach.
I also added support for string concatenation (binary_operator). It is now working both for the standard and parser syntax.

@kieran-ryan Should I open a different MR, or will you allow me to push to this branch/MR?

2025-05-14 15:24 UTC, neskk commented
@luke-hill I think we can close this MR as https://github.com/cucumber/language-service/pull/236 was based of this and superseeds it. Thanks ;)

2025-05-14 15:57 UTC, closed without merging